// Code generated by schema-generate. DO NOT EDIT.

package R4

import (
    "encoding/json"
    "fmt"
    "bytes"
    "errors"
)

// ClaimDetail A provider issued list of professional services and products which have been provided, or are to be provided, to a patient which is sent to an insurer for reimbursement.
type ClaimDetail struct {

  // Code to identify the general type of benefits under which products and services are provided.
  Category *CodeableConcept `json:"category,omitempty"`

  // May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
  Extension []*Extension `json:"extension,omitempty"`

  // A real number that represents a multiplier used in determining the overall value of services delivered and/or goods received. The concept of a Factor allows for a discount or surcharge multiplier to be applied to a monetary amount.
  Factor float64 `json:"factor,omitempty"`

  // Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
  Id string `json:"id,omitempty"`

  // Item typification or modifiers codes to convey additional context for the product or service.
  Modifier []*CodeableConcept `json:"modifier,omitempty"`

  // May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element's descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.
  // 
  // Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).
  ModifierExtension []*Extension `json:"modifierExtension,omitempty"`

  // The quantity times the unit price for an additional service or product or charge.
  Net *Money `json:"net,omitempty"`

  // When the value is a group code then this item collects a set of related claim details, otherwise this contains the product, service, drug or other billing code for the item.
  ProductOrService *CodeableConcept `json:"productOrService"`

  // Identifies the program under which this may be recovered.
  ProgramCode []*CodeableConcept `json:"programCode,omitempty"`

  // The number of repetitions of a service or product.
  Quantity *Quantity `json:"quantity,omitempty"`

  // The type of revenue or cost center providing the product and/or service.
  Revenue *CodeableConcept `json:"revenue,omitempty"`

  // A number to uniquely identify item entries.
  Sequence float64 `json:"sequence,omitempty"`

  // A claim detail line. Either a simple (a product or service) or a 'group' of sub-details which are simple items.
  SubDetail []*ClaimSubDetail `json:"subDetail,omitempty"`

  // Unique Device Identifiers associated with this line item.
  Udi []*Reference `json:"udi,omitempty"`

  // If the item is not a group then this is the fee for the product or service, otherwise this is the total of the fees for the details of the group.
  UnitPrice *Money `json:"unitPrice,omitempty"`
}

func (strct *ClaimDetail) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // Marshal the "category" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"category\": ")
	if tmp, err := json.Marshal(strct.Category); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "extension" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"extension\": ")
	if tmp, err := json.Marshal(strct.Extension); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "factor" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"factor\": ")
	if tmp, err := json.Marshal(strct.Factor); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "id" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"id\": ")
	if tmp, err := json.Marshal(strct.Id); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "modifier" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"modifier\": ")
	if tmp, err := json.Marshal(strct.Modifier); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "modifierExtension" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"modifierExtension\": ")
	if tmp, err := json.Marshal(strct.ModifierExtension); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "net" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"net\": ")
	if tmp, err := json.Marshal(strct.Net); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "ProductOrService" field is required
    if strct.ProductOrService == nil {
        return nil, errors.New("productOrService is a required field")
    }
    // Marshal the "productOrService" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"productOrService\": ")
	if tmp, err := json.Marshal(strct.ProductOrService); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "programCode" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"programCode\": ")
	if tmp, err := json.Marshal(strct.ProgramCode); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "quantity" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"quantity\": ")
	if tmp, err := json.Marshal(strct.Quantity); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "revenue" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"revenue\": ")
	if tmp, err := json.Marshal(strct.Revenue); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "sequence" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"sequence\": ")
	if tmp, err := json.Marshal(strct.Sequence); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "subDetail" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"subDetail\": ")
	if tmp, err := json.Marshal(strct.SubDetail); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "udi" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"udi\": ")
	if tmp, err := json.Marshal(strct.Udi); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "unitPrice" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"unitPrice\": ")
	if tmp, err := json.Marshal(strct.UnitPrice); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *ClaimDetail) UnmarshalJSON(b []byte) error {
    productOrServiceReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "category":
            if err := json.Unmarshal([]byte(v), &strct.Category); err != nil {
                return err
             }
        case "extension":
            if err := json.Unmarshal([]byte(v), &strct.Extension); err != nil {
                return err
             }
        case "factor":
            if err := json.Unmarshal([]byte(v), &strct.Factor); err != nil {
                return err
             }
        case "id":
            if err := json.Unmarshal([]byte(v), &strct.Id); err != nil {
                return err
             }
        case "modifier":
            if err := json.Unmarshal([]byte(v), &strct.Modifier); err != nil {
                return err
             }
        case "modifierExtension":
            if err := json.Unmarshal([]byte(v), &strct.ModifierExtension); err != nil {
                return err
             }
        case "net":
            if err := json.Unmarshal([]byte(v), &strct.Net); err != nil {
                return err
             }
        case "productOrService":
            if err := json.Unmarshal([]byte(v), &strct.ProductOrService); err != nil {
                return err
             }
            productOrServiceReceived = true
        case "programCode":
            if err := json.Unmarshal([]byte(v), &strct.ProgramCode); err != nil {
                return err
             }
        case "quantity":
            if err := json.Unmarshal([]byte(v), &strct.Quantity); err != nil {
                return err
             }
        case "revenue":
            if err := json.Unmarshal([]byte(v), &strct.Revenue); err != nil {
                return err
             }
        case "sequence":
            if err := json.Unmarshal([]byte(v), &strct.Sequence); err != nil {
                return err
             }
        case "subDetail":
            if err := json.Unmarshal([]byte(v), &strct.SubDetail); err != nil {
                return err
             }
        case "udi":
            if err := json.Unmarshal([]byte(v), &strct.Udi); err != nil {
                return err
             }
        case "unitPrice":
            if err := json.Unmarshal([]byte(v), &strct.UnitPrice); err != nil {
                return err
             }
        default:
            return fmt.Errorf("additional property not allowed: \"" + k + "\"")
        }
    }
    // check if productOrService (a required property) was received
    if !productOrServiceReceived {
        return errors.New("\"productOrService\" is required but was not present")
    }
    return nil
}
