// Code generated by schema-generate. DO NOT EDIT.

package R4

import (
    "bytes"
    "encoding/json"
    "fmt"
)

// CoverageEligibilityRequestItem The CoverageEligibilityRequest provides patient and insurance coverage information to an insurer for them to respond, in the form of an CoverageEligibilityResponse, with information regarding whether the stated coverage is valid and in-force and optionally to provide the insurance details of the policy.
type CoverageEligibilityRequestItem struct {

  // Code to identify the general type of benefits under which products and services are provided.
  Category *CodeableConcept `json:"category,omitempty"`

  // The plan/proposal/order describing the proposed service in detail.
  Detail []*Reference `json:"detail,omitempty"`

  // Patient diagnosis for which care is sought.
  Diagnosis []*CoverageEligibilityRequestDiagnosis `json:"diagnosis,omitempty"`

  // May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
  Extension []*Extension `json:"extension,omitempty"`

  // Facility where the services will be provided.
  Facility *Reference `json:"facility,omitempty"`

  // Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
  Id string `json:"id,omitempty"`

  // Item typification or modifiers codes to convey additional context for the product or service.
  Modifier []*CodeableConcept `json:"modifier,omitempty"`

  // May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element's descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.
  // 
  // Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).
  ModifierExtension []*Extension `json:"modifierExtension,omitempty"`

  // This contains the product, service, drug or other billing code for the item.
  ProductOrService *CodeableConcept `json:"productOrService,omitempty"`

  // The practitioner who is responsible for the product or service to be rendered to the patient.
  Provider *Reference `json:"provider,omitempty"`

  // The number of repetitions of a service or product.
  Quantity *Quantity `json:"quantity,omitempty"`

  // Exceptions, special conditions and supporting information applicable for this service or product line.
  SupportingInfoSequence []float64 `json:"supportingInfoSequence,omitempty"`

  // The amount charged to the patient by the provider for a single unit.
  UnitPrice *Money `json:"unitPrice,omitempty"`
}

func (strct *CoverageEligibilityRequestItem) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // Marshal the "category" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"category\": ")
	if tmp, err := json.Marshal(strct.Category); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "detail" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"detail\": ")
	if tmp, err := json.Marshal(strct.Detail); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "diagnosis" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"diagnosis\": ")
	if tmp, err := json.Marshal(strct.Diagnosis); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "extension" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"extension\": ")
	if tmp, err := json.Marshal(strct.Extension); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "facility" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"facility\": ")
	if tmp, err := json.Marshal(strct.Facility); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "id" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"id\": ")
	if tmp, err := json.Marshal(strct.Id); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "modifier" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"modifier\": ")
	if tmp, err := json.Marshal(strct.Modifier); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "modifierExtension" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"modifierExtension\": ")
	if tmp, err := json.Marshal(strct.ModifierExtension); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "productOrService" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"productOrService\": ")
	if tmp, err := json.Marshal(strct.ProductOrService); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "provider" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"provider\": ")
	if tmp, err := json.Marshal(strct.Provider); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "quantity" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"quantity\": ")
	if tmp, err := json.Marshal(strct.Quantity); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "supportingInfoSequence" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"supportingInfoSequence\": ")
	if tmp, err := json.Marshal(strct.SupportingInfoSequence); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "unitPrice" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"unitPrice\": ")
	if tmp, err := json.Marshal(strct.UnitPrice); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *CoverageEligibilityRequestItem) UnmarshalJSON(b []byte) error {
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "category":
            if err := json.Unmarshal([]byte(v), &strct.Category); err != nil {
                return err
             }
        case "detail":
            if err := json.Unmarshal([]byte(v), &strct.Detail); err != nil {
                return err
             }
        case "diagnosis":
            if err := json.Unmarshal([]byte(v), &strct.Diagnosis); err != nil {
                return err
             }
        case "extension":
            if err := json.Unmarshal([]byte(v), &strct.Extension); err != nil {
                return err
             }
        case "facility":
            if err := json.Unmarshal([]byte(v), &strct.Facility); err != nil {
                return err
             }
        case "id":
            if err := json.Unmarshal([]byte(v), &strct.Id); err != nil {
                return err
             }
        case "modifier":
            if err := json.Unmarshal([]byte(v), &strct.Modifier); err != nil {
                return err
             }
        case "modifierExtension":
            if err := json.Unmarshal([]byte(v), &strct.ModifierExtension); err != nil {
                return err
             }
        case "productOrService":
            if err := json.Unmarshal([]byte(v), &strct.ProductOrService); err != nil {
                return err
             }
        case "provider":
            if err := json.Unmarshal([]byte(v), &strct.Provider); err != nil {
                return err
             }
        case "quantity":
            if err := json.Unmarshal([]byte(v), &strct.Quantity); err != nil {
                return err
             }
        case "supportingInfoSequence":
            if err := json.Unmarshal([]byte(v), &strct.SupportingInfoSequence); err != nil {
                return err
             }
        case "unitPrice":
            if err := json.Unmarshal([]byte(v), &strct.UnitPrice); err != nil {
                return err
             }
        default:
            return fmt.Errorf("additional property not allowed: \"" + k + "\"")
        }
    }
    return nil
}
