// Code generated by schema-generate. DO NOT EDIT.

package R4

import (
    "bytes"
    "encoding/json"
    "fmt"
)

// EncounterHospitalization An interaction between a patient and healthcare provider(s) for the purpose of providing healthcare service(s) or assessing the health status of a patient.
type EncounterHospitalization struct {

  // From where patient was admitted (physician referral, transfer).
  AdmitSource *CodeableConcept `json:"admitSource,omitempty"`

  // Location/organization to which the patient is discharged.
  Destination *Reference `json:"destination,omitempty"`

  // Diet preferences reported by the patient.
  DietPreference []*CodeableConcept `json:"dietPreference,omitempty"`

  // Category or kind of location after discharge.
  DischargeDisposition *CodeableConcept `json:"dischargeDisposition,omitempty"`

  // May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
  Extension []*Extension `json:"extension,omitempty"`

  // Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
  Id string `json:"id,omitempty"`

  // May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element's descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.
  // 
  // Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).
  ModifierExtension []*Extension `json:"modifierExtension,omitempty"`

  // The location/organization from which the patient came before admission.
  Origin *Reference `json:"origin,omitempty"`

  // Pre-admission identifier.
  PreAdmissionIdentifier *Identifier `json:"preAdmissionIdentifier,omitempty"`

  // Whether this hospitalization is a readmission and why if known.
  ReAdmission *CodeableConcept `json:"reAdmission,omitempty"`

  // Any special requests that have been made for this hospitalization encounter, such as the provision of specific equipment or other things.
  SpecialArrangement []*CodeableConcept `json:"specialArrangement,omitempty"`

  // Special courtesies (VIP, board member).
  SpecialCourtesy []*CodeableConcept `json:"specialCourtesy,omitempty"`
}

func (strct *EncounterHospitalization) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // Marshal the "admitSource" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"admitSource\": ")
	if tmp, err := json.Marshal(strct.AdmitSource); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "destination" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"destination\": ")
	if tmp, err := json.Marshal(strct.Destination); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "dietPreference" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"dietPreference\": ")
	if tmp, err := json.Marshal(strct.DietPreference); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "dischargeDisposition" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"dischargeDisposition\": ")
	if tmp, err := json.Marshal(strct.DischargeDisposition); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "extension" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"extension\": ")
	if tmp, err := json.Marshal(strct.Extension); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "id" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"id\": ")
	if tmp, err := json.Marshal(strct.Id); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "modifierExtension" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"modifierExtension\": ")
	if tmp, err := json.Marshal(strct.ModifierExtension); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "origin" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"origin\": ")
	if tmp, err := json.Marshal(strct.Origin); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "preAdmissionIdentifier" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"preAdmissionIdentifier\": ")
	if tmp, err := json.Marshal(strct.PreAdmissionIdentifier); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "reAdmission" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"reAdmission\": ")
	if tmp, err := json.Marshal(strct.ReAdmission); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "specialArrangement" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"specialArrangement\": ")
	if tmp, err := json.Marshal(strct.SpecialArrangement); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "specialCourtesy" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"specialCourtesy\": ")
	if tmp, err := json.Marshal(strct.SpecialCourtesy); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *EncounterHospitalization) UnmarshalJSON(b []byte) error {
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "admitSource":
            if err := json.Unmarshal([]byte(v), &strct.AdmitSource); err != nil {
                return err
             }
        case "destination":
            if err := json.Unmarshal([]byte(v), &strct.Destination); err != nil {
                return err
             }
        case "dietPreference":
            if err := json.Unmarshal([]byte(v), &strct.DietPreference); err != nil {
                return err
             }
        case "dischargeDisposition":
            if err := json.Unmarshal([]byte(v), &strct.DischargeDisposition); err != nil {
                return err
             }
        case "extension":
            if err := json.Unmarshal([]byte(v), &strct.Extension); err != nil {
                return err
             }
        case "id":
            if err := json.Unmarshal([]byte(v), &strct.Id); err != nil {
                return err
             }
        case "modifierExtension":
            if err := json.Unmarshal([]byte(v), &strct.ModifierExtension); err != nil {
                return err
             }
        case "origin":
            if err := json.Unmarshal([]byte(v), &strct.Origin); err != nil {
                return err
             }
        case "preAdmissionIdentifier":
            if err := json.Unmarshal([]byte(v), &strct.PreAdmissionIdentifier); err != nil {
                return err
             }
        case "reAdmission":
            if err := json.Unmarshal([]byte(v), &strct.ReAdmission); err != nil {
                return err
             }
        case "specialArrangement":
            if err := json.Unmarshal([]byte(v), &strct.SpecialArrangement); err != nil {
                return err
             }
        case "specialCourtesy":
            if err := json.Unmarshal([]byte(v), &strct.SpecialCourtesy); err != nil {
                return err
             }
        default:
            return fmt.Errorf("additional property not allowed: \"" + k + "\"")
        }
    }
    return nil
}
