// Code generated by schema-generate. DO NOT EDIT.

package R4

import (
    "errors"
    "encoding/json"
    "fmt"
    "bytes"
)

// MedicinalProductPharmaceuticalRouteOfAdministration A pharmaceutical product described in terms of its composition and dose form.
type MedicinalProductPharmaceuticalRouteOfAdministration struct {

  // Coded expression for the route.
  Code *CodeableConcept `json:"code"`

  // May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
  Extension []*Extension `json:"extension,omitempty"`

  // The first dose (dose quantity) administered in humans can be specified, for a product under investigation, using a numerical value and its unit of measurement.
  FirstDose *Quantity `json:"firstDose,omitempty"`

  // Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
  Id string `json:"id,omitempty"`

  // The maximum dose per day (maximum dose quantity to be administered in any one 24-h period) that can be administered as per the protocol referenced in the clinical trial authorisation.
  MaxDosePerDay *Quantity `json:"maxDosePerDay,omitempty"`

  // The maximum dose per treatment period that can be administered as per the protocol referenced in the clinical trial authorisation.
  MaxDosePerTreatmentPeriod *Ratio `json:"maxDosePerTreatmentPeriod,omitempty"`

  // The maximum single dose that can be administered as per the protocol of a clinical trial can be specified using a numerical value and its unit of measurement.
  MaxSingleDose *Quantity `json:"maxSingleDose,omitempty"`

  // The maximum treatment period during which an Investigational Medicinal Product can be administered as per the protocol referenced in the clinical trial authorisation.
  MaxTreatmentPeriod *Duration `json:"maxTreatmentPeriod,omitempty"`

  // May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element's descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.
  // 
  // Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).
  ModifierExtension []*Extension `json:"modifierExtension,omitempty"`

  // A species for which this route applies.
  TargetSpecies []*MedicinalProductPharmaceuticalTargetSpecies `json:"targetSpecies,omitempty"`
}

func (strct *MedicinalProductPharmaceuticalRouteOfAdministration) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Code" field is required
    if strct.Code == nil {
        return nil, errors.New("code is a required field")
    }
    // Marshal the "code" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"code\": ")
	if tmp, err := json.Marshal(strct.Code); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "extension" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"extension\": ")
	if tmp, err := json.Marshal(strct.Extension); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "firstDose" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"firstDose\": ")
	if tmp, err := json.Marshal(strct.FirstDose); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "id" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"id\": ")
	if tmp, err := json.Marshal(strct.Id); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "maxDosePerDay" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"maxDosePerDay\": ")
	if tmp, err := json.Marshal(strct.MaxDosePerDay); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "maxDosePerTreatmentPeriod" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"maxDosePerTreatmentPeriod\": ")
	if tmp, err := json.Marshal(strct.MaxDosePerTreatmentPeriod); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "maxSingleDose" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"maxSingleDose\": ")
	if tmp, err := json.Marshal(strct.MaxSingleDose); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "maxTreatmentPeriod" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"maxTreatmentPeriod\": ")
	if tmp, err := json.Marshal(strct.MaxTreatmentPeriod); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "modifierExtension" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"modifierExtension\": ")
	if tmp, err := json.Marshal(strct.ModifierExtension); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "targetSpecies" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"targetSpecies\": ")
	if tmp, err := json.Marshal(strct.TargetSpecies); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *MedicinalProductPharmaceuticalRouteOfAdministration) UnmarshalJSON(b []byte) error {
    codeReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "code":
            if err := json.Unmarshal([]byte(v), &strct.Code); err != nil {
                return err
             }
            codeReceived = true
        case "extension":
            if err := json.Unmarshal([]byte(v), &strct.Extension); err != nil {
                return err
             }
        case "firstDose":
            if err := json.Unmarshal([]byte(v), &strct.FirstDose); err != nil {
                return err
             }
        case "id":
            if err := json.Unmarshal([]byte(v), &strct.Id); err != nil {
                return err
             }
        case "maxDosePerDay":
            if err := json.Unmarshal([]byte(v), &strct.MaxDosePerDay); err != nil {
                return err
             }
        case "maxDosePerTreatmentPeriod":
            if err := json.Unmarshal([]byte(v), &strct.MaxDosePerTreatmentPeriod); err != nil {
                return err
             }
        case "maxSingleDose":
            if err := json.Unmarshal([]byte(v), &strct.MaxSingleDose); err != nil {
                return err
             }
        case "maxTreatmentPeriod":
            if err := json.Unmarshal([]byte(v), &strct.MaxTreatmentPeriod); err != nil {
                return err
             }
        case "modifierExtension":
            if err := json.Unmarshal([]byte(v), &strct.ModifierExtension); err != nil {
                return err
             }
        case "targetSpecies":
            if err := json.Unmarshal([]byte(v), &strct.TargetSpecies); err != nil {
                return err
             }
        default:
            return fmt.Errorf("additional property not allowed: \"" + k + "\"")
        }
    }
    // check if code (a required property) was received
    if !codeReceived {
        return errors.New("\"code\" is required but was not present")
    }
    return nil
}
